/**
 * This file is part of the IPK Project 1 - OMEGA: L4 Scanner.
 * // 23.3. 2026 IPK 2026, FIT VUT Brno
 *  Author: Kristian Rucek > xrucekk00
 */

#include <criterion/criterion.h>
#include <criterion/logging.h>
#include <sysexits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/wait.h>
#include <time.h>

#define BINARY "./ipk-L4-scan"
#define CLR_RESET  "\x1b[0m"
#define CLR_CYAN   "\x1b[36m"
#define CLR_YELLOW "\x1b[33m"
#define CLR_RED    "\x1b[31m"

char detected_iface[32] = {0};

void suite_setup(void) {
    FILE *fp = popen(BINARY " -i | grep -v 'lo' | head -n 1", "r");
    if (!fp || fscanf(fp, "%31s", detected_iface) != 1) strcpy(detected_iface, "eth0");
    if (fp) pclose(fp);
    cr_log_info(CLR_CYAN "Detected active interface: %s" CLR_RESET, detected_iface);
}

TestSuite(network_errors, .init = suite_setup);

// Helper: Run command and measure execution time in milliseconds
typedef struct {
    int exit_code;
    long duration_ms;
    char output[4096];
} RunResult;


// This function was generated by AI, after specific instructions for testing requirements
RunResult run_app_timed(const char* args) {
    RunResult result = {0};
    char processed[512], command[1024];
    
    // Replace IFACE placeholder
    char *placeholder = strstr(args, "IFACE");
    if (placeholder) {
        size_t prefix_len = placeholder - args;
        sprintf(processed, "%.*s%s%s", (int)prefix_len, args, detected_iface, placeholder + 5);
    } else {
        strcpy(processed, args);
    }
    
    // Build command with output capture
    snprintf(command, sizeof(command), "sudo " BINARY " %s 2>&1", processed);
    
    // Measure time
    struct timespec start, end;
    clock_gettime(CLOCK_MONOTONIC, &start);
    
    FILE *fp = popen(command, "r");
    if (fp) {
        size_t len = fread(result.output, 1, sizeof(result.output) - 1, fp);
        result.output[len] = '\0';
        
        int status = pclose(fp);
        result.exit_code = WEXITSTATUS(status);
    }
    
    clock_gettime(CLOCK_MONOTONIC, &end);
    result.duration_ms = (end.tv_sec - start.tv_sec) * 1000 + 
                         (end.tv_nsec - start.tv_nsec) / 1000000;
    
    fprintf(stderr, CLR_YELLOW "[EXEC] " CLR_RESET "%s (Exit: %d, Time: %ldms)\n", 
            command, result.exit_code, result.duration_ms);
    
    return result;
}

/* ==========================================================================
   HOSTNAME RESOLUTION TESTS
   ========================================================================== */

Test(network_errors, valid_hostname_localhost) {
    RunResult r = run_app_timed("-i IFACE -t 80 localhost");
    cr_assert_eq(r.exit_code, EX_OK, "localhost should be resolved successfully");
}

Test(network_errors, valid_hostname_ipv4) {
    RunResult r = run_app_timed("-i IFACE -t 80 127.0.0.1");
    cr_assert_eq(r.exit_code, EX_OK, "IP literal should work");
}

Test(network_errors, invalid_hostname) {
    RunResult r = run_app_timed("-i IFACE -t 80 Invalid-hostname");
    cr_assert_neq(r.exit_code, EX_OK, "Invalid hostname should fail");
}

Test(network_errors, empty_hostname) {
    RunResult r = run_app_timed("-i IFACE -t 80 '' ");
    cr_assert_neq(r.exit_code, EX_OK, "Empty hostname should return error");
}

Test(network_errors, ipv6_localhost) {
    RunResult r = run_app_timed("-i lo -t 80 ::1");
    cr_assert_eq(r.exit_code, EX_OK, "IPv6 localhost should work");
}

/* ==========================================================================
   TIMEOUT TESTS
   ========================================================================== */

   // Quality of this tests is questionable
   // I am not sure how to correctly test timeout behavior
   // However, they do test the timeout functionality at least with some level of reasonability
Test(network_errors, timeout_default_reasonable, .timeout = 5) {
    // Default timeout is 1000ms, scanning 1 port should take ~1 second
    RunResult r = run_app_timed("-i IFACE -t 9999 127.0.0.1");
    cr_assert_eq(r.exit_code, EX_OK);
    cr_assert_lt(r.duration_ms, 3000, "Default timeout scan should complete quickly");
}

Test(network_errors, timeout_custom_short, .timeout = 5) {
    // Set very short timeout (100ms)
    RunResult r = run_app_timed("-i IFACE -t 9999 -w 100 127.0.0.1");
    cr_assert_eq(r.exit_code, EX_OK);
    // Should complete faster than default
    cr_assert_lt(r.duration_ms, 2000, "Short timeout should complete quickly");
}

Test(network_errors, timeout_custom_long, .timeout = 5) {
    // Set longer timeout (2000ms)
    RunResult r = run_app_timed("-i IFACE -t 9999 -w 2000 127.0.0.1");
    cr_assert_eq(r.exit_code, EX_OK);
    cr_assert_gt(r.duration_ms, 2000, "Long timeout should take longer");
}

Test(network_errors, timeout_multiple_ports_scales, .timeout = 5) {
    RunResult r = run_app_timed("-i IFACE -t 9997,9998,9999 -w 500 127.0.0.1");
    cr_assert_eq(r.exit_code, EX_OK);
    cr_assert_gt(r.duration_ms, 1500, "Multiple ports should scale with timeout");
}

/* ==========================================================================
   UNREACHABLE HOST TESTS
   ========================================================================== */

Test(network_errors, unreachable_ip_filtered, .timeout = 5) {
    RunResult r = run_app_timed("-i IFACE -t 80 -w 500 192.0.2.1");
    cr_assert_eq(r.exit_code, EX_OK);
    cr_assert(strstr(r.output, "filtered") != NULL, "Unreachable host should show filtered");
}

Test(network_errors, localhost_closed_port) {
    // Port 9 (discard) is typically closed on localhost
    RunResult r = run_app_timed("-i lo -t 9 -w 500 127.0.0.1");
    cr_assert_eq(r.exit_code, EX_OK);
    bool has_status = strstr(r.output, "closed") || strstr(r.output, "filtered");
    cr_assert(has_status, "Should report port status");

    RunResult r = run_app_timed("-i lo -u 9 -w 500 127.0.0.1");
    cr_assert_eq(r.exit_code, EX_OK);
    bool has_status = strstr(r.output, "closed") || strstr(r.output, "filtered");
    cr_assert(has_status, "Should report port status");
}

/* ==========================================================================
   MIXED PROTOCOL TESTS
   ========================================================================== */

Test(network_errors, tcp_and_udp_same_host, .timeout = 5) {
    RunResult r = run_app_timed("-i lo -t 80 -u 53 -w 500 localhost");
    cr_assert_eq(r.exit_code, EX_OK);
    // Should have both tcp and udp in output
    cr_assert(strstr(r.output, "tcp") != NULL, "Should scan TCP");
    cr_assert(strstr(r.output, "udp") != NULL, "Should scan UDP");
}

Test(network_errors, udp_timeout_behavior, .timeout = 5) {
    // UDP to closed port on localhost should be rejected with icmp by OS
    RunResult r = run_app_timed("-i lo -u 9999 -w 500 127.0.0.1");
    cr_assert_eq(r.exit_code, EX_OK);
    cr_assert(strstr(r.output, "udp closed") != NULL, "Should scan UDP port");
}

/* ==========================================================================
   EDGE CASES
   ========================================================================== */

Test(network_errors, scan_port_1, .timeout = 5) {
    // Port 1 is valid minimum
    RunResult r = run_app_timed("-i lo -t 1 -w 500 localhost");
    cr_assert_eq(r.exit_code, EX_OK);
    cr_assert(strstr(r.output, " 1 ") != NULL, "Should scan port 1");
}

Test(network_errors, scan_port_65535, .timeout = 5) {
    // Port 65535 is valid maximum
    RunResult r = run_app_timed("-i lo -t 65535 -w 500 localhost");
    cr_assert_eq(r.exit_code, EX_OK);
    cr_assert(strstr(r.output, "65535") != NULL, "Should scan port 65535");
}

Test(network_errors, rapid_succession_scans, .timeout = 5) {
    RunResult r1 = run_app_timed("-i lo -t 80 -w 200 localhost");
    RunResult r2 = run_app_timed("-i lo -t 443 -w 200 localhost");
    
    cr_assert_eq(r1.exit_code, EX_OK, "First scan should succeed");
    cr_assert_eq(r2.exit_code, EX_OK, "Second scan should succeed");
}
